const IMG={
  hero:"https://vakkerlight.com/cdn/shop/files/17784867849861.png?v=1778486798&width=2400",
  room:"https://vakkerlight.com/cdn/shop/files/1774431691540.png?v=1774431703&width=2400",
  chandelier:"https://vakkerlight.com/cdn/shop/files/Celestial_Alabaster_Round_Chandelier__1.jpg?v=1712645929&width=1080",
  chandelier2:"https://vakkerlight.com/cdn/shop/files/Celestial_Alabaster_Round_Chandelier__28.jpg?v=1712645932&width=1080"
};
const products=[
  ["Celestial Alabaster Chandelier","From $1,196",IMG.chandelier,"Best Seller"],
  ["Silken Lotus Pendant","From $198",IMG.hero,"New"],
  ["Horizon Bloom Chandelier","From $248",IMG.room,"Signature"],
  ["Marcellus Arc Floor Lamp","From $328",IMG.chandelier2,"New"]
];
const productCards=()=>products.map((p,i)=>`<article class="product-card reveal" data-product="${i}"><div class="product-image"><img src="${p[2]}" alt="${p[0]}"><span class="badge">${p[3]}</span><span class="quick-add">View piece</span></div><div class="product-meta"><h3>${p[0]}</h3><p>${p[1]}</p></div></article>`).join("");
const home=()=>`
<section class="hero"><div class="hero-copy"><p class="eyebrow">Vakkerlight · Collection 2026</p><h1 class="display">The Art of<br>Atmosphere.</h1><p class="body-large">Sculptural lighting shaped by honest materials, quiet detail, and the way a room feels after dark.</p><a class="link-arrow" href="#collection">Explore the collection <span>↗</span></a></div><figure class="hero-media"><img src="${IMG.hero}" alt="Vakkerlight alabaster lighting in an elegant interior"><span class="hero-index">No. 01 / Alabaster</span></figure></section>
<div class="marquee"><div class="marquee-track">ALABASTER <span>✦</span> SILK <span>✦</span> TRAVERTINE <span>✦</span> HAND-FINISHED BRASS <span>✦</span> ALABASTER <span>✦</span> SILK <span>✦</span> TRAVERTINE <span>✦</span> HAND-FINISHED BRASS <span>✦</span></div></div>
<section class="section"><div class="section-heading reveal"><div><p class="eyebrow">Curated edits</p><h2 class="section-title">Material, made luminous.</h2></div><a class="link-arrow" href="#collection">View all</a></div><div class="editorial-grid"><article class="editorial-card reveal"><img class="image-cover" src="${IMG.chandelier2}" alt="Alabaster chandelier"><div class="card-copy"><p class="eyebrow">Natural stone</p><h3>The Alabaster Edit</h3><a class="link-arrow" href="#collection">Discover</a></div></article><article class="editorial-card small reveal"><img class="image-cover" src="${IMG.room}" alt="Lighting for considered rooms"><div class="card-copy"><p class="eyebrow">Spaces with soul</p><h3>Light for Living</h3><a class="link-arrow" href="#collection">Shop by room</a></div></article></div></section>
<section class="section"><div class="section-heading reveal"><div><p class="eyebrow">Selected pieces</p><h2 class="section-title">Objects of light.</h2></div><a class="link-arrow" href="#collection">See all pieces</a></div><div class="product-grid">${productCards()}</div></section>
<section class="manifesto"><div class="manifesto-copy reveal"><p class="eyebrow">Our point of view</p><h2 class="section-title">Less spectacle.<br>More presence.</h2><p class="body-large">We choose lighting for what it brings to a space: warmth, balance, and an enduring sense of place.</p><a class="link-arrow" href="#about">Enter our world</a></div><img src="${IMG.room}" alt="A softly lit Vakkerlight interior"></section>
<section class="service-strip"><div><h3>Complimentary Shipping</h3><p>Standard delivery on every order.</p></div><div><h3>60-Day Returns</h3><p>Time to see the piece in your space.</p></div><div><h3>Lighting Advice</h3><p>Personal sizing and placement support.</p></div><div><h3>Custom & Trade</h3><p>Dedicated service for considered projects.</p></div></section>`;
const collection=()=>`<section class="collection-hero"><p class="eyebrow">The lighting collection</p><h1 class="display">Sculptural<br>Essentials.</h1><p class="body-large">A considered edit of pendants, chandeliers, wall lights and portable pieces—chosen for material, proportion and atmosphere.</p></section><div class="filters"><span>Filter +</span><span>52 pieces</span><span>Sort: Featured</span></div><section class="collection-wrap"><div class="product-grid">${productCards()}${productCards()}</div></section>`;
const product=()=>`<section class="product-layout"><div class="product-gallery"><img src="${IMG.chandelier}" alt="Celestial Alabaster Chandelier front view"><img src="${IMG.chandelier2}" alt="Celestial Alabaster Chandelier detail"><img src="${IMG.room}" alt="Chandelier in a dining space"><img src="${IMG.hero}" alt="Alabaster detail"></div><div class="product-info"><p class="eyebrow">Vakkerlight signature</p><h1>Celestial Alabaster Chandelier</h1><p class="rating">★★★★★ &nbsp; 26 considered reviews</p><p class="price">$1,196 <s>$2,400</s></p><p>Hand-cut Spanish alabaster slats create a continuous ring of warm, softly varied light. A sculptural centrepiece with a quiet architectural presence.</p><div class="option-title"><span>Size</span><span>Size guide ↗</span></div><div class="swatches"><button class="active">Ø 17.7″</button><button>Ø 23.6″</button><button>Ø 31.5″</button><button>Two-tier</button></div><div class="option-title"><span>Finish</span><span>Brass / Alabaster</span></div><div class="swatches"><button class="active">Warm Brass</button></div><button class="add-button">Add to selection — $1,196</button><div class="trust-line"><span>Complimentary<br>shipping</span><span>60-day<br>returns</span><span>1-year<br>warranty</span></div><div class="accordions"><div class="accordion open"><button>Design & Materials <span>−</span></button><p>Genuine Spanish alabaster and hand-finished brass. Natural veining makes every piece distinct.</p></div><div class="accordion"><button>Dimensions & Details <span>+</span></button><p>Available from Ø17.7″ to Ø39.4″, including single and two-tier configurations.</p></div><div class="accordion"><button>Delivery & Installation <span>+</span></button><p>Hardwired ceiling installation. Professional installation recommended.</p></div></div></div></section>`;
const journal=()=>`<section class="page-intro"><p class="eyebrow">Ideas & inspiration</p><h1 class="display">The Journal.</h1><p class="body-large">Material notes, rooms worth studying, and practical guidance for choosing light with confidence.</p></section><section class="journal-grid">${[["Natural Stone, Honest Light","How alabaster changes a room after dark.",IMG.chandelier],["The New Warm Modern","Why restraint feels more luxurious now.",IMG.room],["Finding the Right Scale","A practical guide to lighting proportion.",IMG.hero]].map(x=>`<article class="journal-card reveal"><img src="${x[2]}" alt="${x[0]}"><p class="eyebrow">Design notes · 6 min</p><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join("")}</section>`;
const about=()=>`<section class="page-intro"><p class="eyebrow">Our world</p><h1 class="display">Light with<br>lasting presence.</h1></section><section class="about-split"><img src="${IMG.room}" alt="Vakkerlight interior"><div class="about-copy"><p class="eyebrow">The Vakkerlight point of view</p><h2>Chosen slowly.<br>Lived with daily.</h2><p>We believe a fixture should do more than fill a room with light. It should bring proportion, texture and atmosphere—without asking for attention every moment.</p><p>Our collection moves between artisan craft and modern clarity, with a particular focus on natural stone, silk, wood and hand-finished metal.</p><a class="link-arrow" href="#collection">Explore the collection</a></div></section>`;
const routes={home,collection,product,journal,about};
function render(){const key=location.hash.replace("#","")||"home";document.querySelector("#app").innerHTML=(routes[key]||home)();window.scrollTo(0,0);bindDynamic();reveal()}
function reveal(){const ob=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("visible")),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>ob.observe(el))}
function panel(el,state=true){document.querySelector(el).classList.toggle("open",state);document.querySelector(".overlay").classList.toggle("open",state&&el!==".mega-menu"&&el!==".search-panel")}
function bindDynamic(){document.querySelectorAll(".product-card").forEach(c=>c.onclick=()=>location.hash="product");document.querySelectorAll(".swatches button").forEach(b=>b.onclick=()=>{b.parentNode.querySelectorAll("button").forEach(x=>x.classList.remove("active"));b.classList.add("active")});document.querySelectorAll(".accordion button").forEach(b=>b.onclick=()=>b.parentNode.classList.toggle("open"));document.querySelector(".add-button")?.addEventListener("click",addToCart)}
function addToCart(){document.querySelector(".cart-count").textContent="1";document.querySelector(".cart-total").textContent="$1,196";document.querySelector(".cart-content").innerHTML=`<div class="cart-item"><img src="${IMG.chandelier}" alt=""><div><p class="eyebrow">Vakkerlight signature</p><h3>Celestial Alabaster Chandelier</h3><p>Ø 17.7″ · Warm Brass</p><strong>$1,196</strong></div></div>`;panel(".cart-drawer")}
document.querySelector(".menu-button").onclick=()=>panel(".mega-menu");document.querySelector(".close-menu").onclick=()=>panel(".mega-menu",false);document.querySelector(".search-button").onclick=()=>panel(".search-panel");document.querySelector(".close-search").onclick=()=>panel(".search-panel",false);document.querySelector(".cart-button").onclick=()=>panel(".cart-drawer");document.querySelector(".close-cart").onclick=()=>panel(".cart-drawer",false);document.querySelector(".overlay").onclick=()=>panel(".cart-drawer",false);document.querySelector(".newsletter").onsubmit=e=>{e.preventDefault();e.target.innerHTML="<p>Thank you. Welcome to our world of light.</p>"};window.addEventListener("hashchange",render);render();
